spring:
  application:
    name: book-comment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book-comment-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  pattern:
    console: '%c{1.} [%-5level] %d{HH:mm:ss.SSS} - %msg%n'
