spring:
  application:
    name: eureka-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
        - id: view-history-service
          uri: lb://view-history-service
          predicates:
            - Path=/api/history/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/rating/**
        - id: book-file-service
          uri: lb://book-file-service
          predicates:
            - Path=/api/file/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendation/**
        - id: scroll-service
          uri: lb://scroll-service
          predicates:
            - Path=/api/scroll/**
        - id: scroll-user-view-history-service
          uri: lb://scroll-user-view-history-service
          predicates:
            - Path=/api/user-scroll-view-history/**
        - id: scroll-user-like-service
          uri: lb://scroll-user-like-service
          predicates:
            - Path=/api/user-scroll-like/**
        - id: scroll-recommendation-service
          uri: lb://scroll-recommendation-service
          predicates:
            - Path=/api/user-scroll-recommendation/**
        - id: book-view-count-service
          uri: lb://book-view-count-service
          predicates:
            - Path=/api/book-view-count/**
        - id: book-image-service
          uri: lb://book-image-service
          predicates:
            - Path=/api/image/**
        - id: book-mark-service
          uri: lb://book-mark-service
          predicates:
            - Path=/api/book-mark/**
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: '%c{1.} [%-5level] %d{HH:mm:ss.SSS} - %msg%n'

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000